CREATE TABLE IF NOT EXISTS `am_stopvirus_attempts` (
    `ID` bigint(11) NOT NULL AUTO_INCREMENT,
    `DATE_CREATE` datetime NOT NULL,
    `REQUEST_TYPE` varchar(10) DEFAULT NULL,
    `HTTP_HOST` varchar(255) DEFAULT NULL,
    `REQUEST_URI` varchar(255) DEFAULT NULL,
    `SCRIPT_FILENAME` varchar(255) DEFAULT NULL,
    `FROM_IP` varchar(45) DEFAULT NULL,
    `FROM_HOST` varchar(255) DEFAULT NULL,
    `FROM_USER_AGENT` varchar(255) DEFAULT NULL,
    `IS_DETECT_VIRUS` char(1) NOT NULL DEFAULT 'N',
    `DATA_HEADER` longtext DEFAULT NULL,
    `DATA_QUERY` longtext DEFAULT NULL,
    `DATA_BODY` longtext DEFAULT NULL,
    `MATCH_SIGNATURES` text DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_DATE_CREATE` (`DATE_CREATE`),
    KEY `IX_IS_DETECT_VIRUS` (`IS_DETECT_VIRUS`)
);

CREATE TABLE IF NOT EXISTS `am_stopvirus_signatures` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` varchar(255) DEFAULT NULL,
    `SIGNATURES` TEXT NULL DEFAULT NULL,
    `IS_DEFAULT` CHAR(1) NOT NULL DEFAULT 'N',
    PRIMARY KEY (`ID`),
    INDEX `IX_IS_DEFAULT` (`IS_DEFAULT`)
);

CREATE TABLE IF NOT EXISTS `am_stopvirus_rules` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` varchar(255) DEFAULT NULL,
    `ACTIVE` CHAR(1) NOT NULL DEFAULT 'Y',
    `SORT` INT NOT NULL DEFAULT '1000',
    `ACTION` CHAR(1) NOT NULL DEFAULT 'D',
    `USE_DEFAULT_SIGNATURE` CHAR(1) NOT NULL DEFAULT 'Y',
    `SIGNATURE_ID` INT NULL DEFAULT NULL,
    `STORE_POST_BODY` CHAR(1) NOT NULL DEFAULT 'Y',
    `MEMORY_LIMIT` INT NULL DEFAULT NULL,
    `PAGE_RULES` LONGTEXT NULL DEFAULT NULL,
    `IP_RULES` LONGTEXT NULL DEFAULT NULL,
    `IP_RULES_VALUES` LONGTEXT NULL DEFAULT NULL,
    PRIMARY KEY (`ID`),
    INDEX `IX_ACTIVE` (`ACTIVE`),
    INDEX `IX_SORT` (`SORT`)
);
