CREATE TABLE IF NOT EXISTS `am_stopvirus_attempts` (
    `ID` bigint(11) NOT NULL AUTO_INCREMENT,
    `DATE_CREATE` datetime NOT NULL,
    `REQUEST_TYPE` varchar(10) DEFAULT NULL,
    `HTTP_HOST` varchar(255) DEFAULT NULL,
    `REQUEST_URI` varchar(255) DEFAULT NULL,
    `SCRIPT_FILENAME` varchar(255) DEFAULT NULL,
    `FROM_IP` varchar(45) DEFAULT NULL,
    `FROM_HOST` varchar(255) DEFAULT NULL,
    `FROM_USER_AGENT` varchar(255) DEFAULT NULL,
    `IS_DETECT_VIRUS` char(1) NOT NULL DEFAULT 'N',
    `DATA_HEADER` longtext DEFAULT NULL,
    `DATA_QUERY` longtext DEFAULT NULL,
    `DATA_BODY` longtext DEFAULT NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_DATE_CREATE` (`DATE_CREATE`),
    KEY `IX_IS_DETECT_VIRUS` (`IS_DETECT_VIRUS`)
);
